[project]
name = "label-centerlines"
version = "2026.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click",
    "fiona>=1.10.0",
    "networkx>=2.1",
    "scipy>=0.17",
    "shapely>=1.8",
    "tqdm",
]

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""

[project.scripts]
label_centerlines = "label_centerlines.cli:main"

[tool.pytest.ini_options]
testpaths = ["test"]

[dependency-groups]
dev = ["pytest", "ruff"]

[tool.ruff]
line-length = 88
exclude = ["test/testdata/syntax_error.py"]

[tool.ruff.lint]
select = ["B", "C90", "E", "F", "W", "T10"]
ignore = ["E203", "E266", "E501", "F403", "F401", "E741"]

[tool.ruff.lint.mccabe]
max-complexity = 18
